name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 9 2 0 05 00 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Running
        run: |
          echo "Running!"