name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * * *" # every 5 minutes 00 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Running
        run: |
          echo "Running!"