name: Scrape IMDb Top 250

on:
  push:
    branches:
      - main
  schedule:
    
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      
        name: Running 21f3001993@ds.study.iitm.ac.in
        run: |
          echo "Running!"
        name: Checkout code
        uses: actions/checkout@v2
        commit: main
